### ISSUE TITLE
ERROR: Fix public key before proceeding

### ISSUE THREAD

**Issue by AlexPotterOnGit** [llamafilm/tesla-http-proxy-addon#51]
**Describe the bug**
Successfully followed configuration and Tesla integration was working fine. Commands to the car was send to the car and actioned. The server was restarted overnight and next day integration doesn't work any more. In the proxy log I see error:
ERROR: Fix public key before proceeding.

Checked https://tesla.mydomainhere.com/.well-known/appspecific/com.tesla.3p.public-key.pem

And it's accessible from outside of home network. 

Using wildcard certificate for my domain to cover both tesla.mydomain.com and ha.mydomain.com

**To Reproduce**
Restart the Tesla Proxy add-on

**Expected behavior**
Tesla integration to control the car via proxy

**Screenshots**

**Environment (please complete the following information):**
 - Home Assistant version: 2024.03.0
 - Home Assistant install method: supervised
 - Addon version: 1.3.4
 - Region: AU
 - Vehicle model and year: Model 3 2024
 - Your public domain name.
Worried to provide to be honest. Please let me know if really required.

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[11:15:01] INFO: Found existing keypair
[11:15:01] INFO: Testing public key...
[11:15:01] ERROR: Fix public key before proceeding.
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped.

**Comment by llamafilm** [comment]
I’m guessing you have auto updates turned on.
I pushed this update yesterday in an attempt to help guide people who were having DNS or certificate issues. But it sounds like I broke something, sorry about that.
Do you have any idea why your domain is not accessible from inside your network? It works for me. Maybe something about hairpin NAT settings?

**Comment by AlexPotterOnGit** [comment]
Appreciated for such a quick reply. 

I did notice I am getting Bad gateway today if trying to connect to the web interface. Not 100% sure if I was connecting from outside of network yesterday. 

Could be NAT related you right. Not getting it often, but with the new DNS name could be. Wondering if tesla.mydomain.com is being used by add-on? I thought it's only must be achievable from outside. May need to check router/firewall rules.

**Comment by llamafilm** [comment]
You can use this command to test from internal and external to help see why it’s failing.

curl -sfD - "https://$DOMAIN/.well-known/appspecific/com.tesla.3p.public-key.pem"

The web UI only works the first time for authentication. After that, Flask is replaced by the command proxy, so that bad gateway error is normal.

**Comment by AlexPotterOnGit** [comment]
Thank you very much, as you pointed out as soon as tesla.mydomain.com has been resolved to HA host (config specific to my local DNS resolution) the error is gone. Unfortunately, Tesla integration still doesn't work, now with "login required" error in debug log. DOn't understand what I am doing wrong. Tried to start Proxy with "Regenerate authentication" switch on, go the new NA_ token, entered into the Tesla integration but still the same error. Happy to open another issue as the initial is resolved. Just not sure if it is related to Tesla integration or Proxy?
Regards

**Comment by llamafilm** [comment]
That login_required error means the refresh token has been used already. It can only be used once. It’s a bug with the Tesla integration reauth config flow but I haven’t been able to find it yet. The easiest fix is to delete the car and add it back again with the new refresh token.
